
FIND_PATH(VIGRA_INCLUDE_DIR impex.hxx PATH_SUFFIXES vigra)

FIND_LIBRARY(VIGRA_LIBRARY NAMES vigraimpex)

INCLUDE(${CMAKE_CURRENT_LIST_DIR}/FindPackageHandleStandardArgs.cmake)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(VIGRA DEFAULT_MSG VIGRA_LIBRARY VIGRA_INCLUDE_DIR)

IF(VIGRA_FOUND)
  SET(VIGRA_LIBRARIES ${VIGRA_LIBRARY})
ENDIF(VIGRA_FOUND)
